### ISSUE TITLE
Missing some runners in Gitlab

### ISSUE THREAD

**Issue by swisskyrepo** [h4wkst3r/SCMKit#1]
Hi, 

The command `SCMKit.exe -s gitlab -m listrunner -c userName:password -u https://gitlab.something.local`, doesn't check for "Shared runners" and "Group Runners" attributed to a repository owned by the current user.

**Comment by h4wkst3r** [comment]
will add this to my list, thank you!

**Comment by h4wkst3r** [comment]
This has now been added in v1.2 release. Thanks for the suggestion @swisskyrepo!
